name: Addition request
description: Request for new entry to vocabulary.
title: "[Addition request]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this addition request!
  - type: input
    id: unique ID
    attributes:
      label: unique ID
      description: add unique ID for the required resource
      placeholder: ex. MY_NEW_RESOURCE
    validations:
      required: false
  - type: checkboxes
    id: does-not-exist
    attributes:
      label: Existence check
      description: I have checked that this new resource is not yet part of the vocabulary.
      options:
        - label: I have checked that this new resource is not yet part of the vocabulary.
          required: true
  - type: checkboxes
    id: uniqueness
    attributes:
      label: Uniqueness check
      description: I have checked that the unique identifier of this resource is indeed unique.
      options:
        - label: I have checked that the unique identifier of this resource is indeed unique.
          required: true