name: Publish Vocabulary

on:
    pull_request:
    release:
        types: [published]


jobs:
    publish-vocabulary:
        if: github.repository != 'eu-parc/vocabulary-template'
        uses: eu-parc/voc2skosmos-workflow/.github/workflows/yml2skos.yml@main
        with:
            ref: ${{ github.ref }}
            namespace: http://www.eirene.eu/Indicator#
            namespace_label: eirene
            linkml_schema: schema/indicator.linkml.yml
            data: data/IndicatorList_data.yml
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}

    ## PICK EITHER ONE OF THE TWO
    #publish-vocabulary:
    #    if: github.repository != 'eu-parc/vocabulary-template'
    #    uses: eu-parc/voc2skosmos-workflow/.github/workflows/yml2skos.yml@main
    #    with:
    #        ref: ${{ github.ref }}
    #        namespace: http://www.placeholder.com/
    #        namespace_label: placeholder
    #        linkml_schema: schema/resource.linkml.yml
    #        data: data/data.yml
    #    secrets:
    #        token: ${{ secrets.GITHUB_TOKEN }}